<div class="footer__logo">
    logoauto
</div>
<div class="footer__menu">
    <a href="#" class="footer__menu_item">Latest Competitions</a>
    <a href="#" class="footer__menu_item">Entry Lists</a>
    <a href="#" class="footer__menu_item">Live Draws</a>
    <a href="#" class="footer__menu_item">Winners</a>
    <a href="#" class="footer__menu_item">Gift Cards</a>
    <a href="#" class="footer__menu_item">How it Works</a>
</div>
